### ISSUE TITLE
对于Join的理解疑惑

### ISSUE THREAD

**Issue by cotide** [hellokaton/anima#43]
> hi~ Anima 很棒！使用过程中觉得Join的使用有点疑惑，望指教 ^^

## 实体

``` code

@Table(name = "table1")
@Data
public class Table1  extends Model {

    @Column(name = "id")
    private int id;

    @Column(name = "no")
    private String no;
}


@Table(name = "table2")
@Data
public class Table2  extends Model {

    @Column(name = "id")
    private int id;

    @Column(name = "name")
    private String name;
}
 
```

## 查询语句

``` code
select * from table1 as a 
left join table2 as b 
where a.no = 'AAA' and b.name ='BBB'
```
用 lambda JOIN 需要如何生成这样的SQL，还是目前只能用bySQL()实现？还有对于Join的as()的用法如何去理解~

**Comment by biezhi** [comment]
anima 的设计是这样的，通过 Java 语法生成的所谓 `join` 不过是将关联做了转换变成了多条 SQL，例子在 [JoinTest](https://github.com/biezhi/anima/blob/master/src/test/java/io/github/biezhi/anima/JoinTest.java)，如果想生成那样的语句需要使用 `bySQL` 方法。

集中 ORM 化会让很多人陷入编程语言的对象和 SQL 的关联关系中，这样反而会让问题更麻烦（使用者总是要思考框架的关联规则是什么？语法是什么？），即便 anima 目前也有像 `JoinTest` 这样的支持，是一些使用者提出的，但我还是从不会用这种方式。

自定义的 SQL 无需和一个 `Model` 对应，字段和返回行中的列保持一致即可，也可以用 `map` 接收，见 [testListMap](https://github.com/biezhi/anima/blob/master/src/test/java/io/github/biezhi/anima/SelectTest.java#L230)。

**Comment by biezhi** [comment]
关于 `join` 在框架中的想法，如果可以做到规则简单、API 易用，我当然会接收这种方案，但目前据我的思考还未诞生可实践的方案，几遍是 Ruby On Rails 或者其他流行的库（如 gorm、ponyorm），里面的概念都有些繁琐。

**Comment by cotide** [comment]
Hi~ 无意发现一个开源项目叫[JaQu](http://www.h2database.com/html/jaqu.html#what_is_jaqu) 里面有一个JOIN 的实现
``` code
private void testSelectManyCompoundFrom2() throws Exception {
        final Customer c = new Customer();
        final Order o = new Order();
        List<CustOrder> orders =
            db.from(c).
            innerJoin(o).on(c.customerId).is(o.customerId).
            where(o.total).smaller(new BigDecimal("500.00")).
            orderBy(1).
            select(new CustOrder() {{
                customerId = c.customerId;
                orderId = o.orderId;
                total = o.total;
            }});
    }
```
这种风格会不会适合anima
